### ISSUE TITLE
Delete the words "icon" and "button" from alt-text

### ISSUE THREAD

**Issue by karelvanoordt** [JEFFKAY16/Portfolio-Website#13]
Your code looks great, you made some helpful implementations 👏 👏 

- However, I think you should omit the words `icon`, `image` and `button` from all your alt text, it is a better practice to not include direct descriptions such as these. Usually, screen readers automatically provide that information. Remove the word button or image or icon from all your alt texts.

**Comment by JEFFKAY16** [comment]
Thank you, Karel.
